// Emits the publishable `dist/` for @behaviors-sh/dsl:
//
//   - dist/index.js     ESM bundle (workspace + non-trivial deps external)
//   - dist/index.d.ts   generated by tsc
//
// Externals are listed so consumers dedupe shared deps (zod,
// object-hash) and so @behaviors-sh/spec is resolved from npm rather
// than inlined.

import { resolve } from "node:path";
import { $ } from "bun";

const root = resolve(import.meta.dir, "..");
const externals = ["@behaviors-sh/spec", "object-hash", "zod"];
const externalArgs = externals.flatMap((e) => ["--external", e]);

console.log("[build] bundling src/index.ts → dist/index.js");
await $`bun build src/index.ts --target node --outdir dist ${externalArgs}`.cwd(
	root,
);

console.log("[build] emitting dist/index.d.ts (tsc)");
await $`bunx tsc -p tsconfig.build.json`.cwd(root);

console.log("[build] done");
