// Emits the publishable `dist/` for @behaviors-sh/spec:
//
//   - dist/index.js              ESM bundle (zod kept external)
//   - dist/index.d.ts            generated by tsc
//   - dist/tree.schema.json      JSON Schema for the tree document
//   - dist/workspace.schema.json JSON Schema for the workspace
//
// The schema files are derived from the live zod schemas via
// `zod.toJSONSchema` so they can't drift from the source of truth.

import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { $ } from "bun";
import { BehaviourNodeSchema, WorkspaceSchema } from "../src/index";

const root = resolve(import.meta.dir, "..");
const distDir = resolve(root, "dist");
await mkdir(distDir, { recursive: true });

console.log("[build] bundling src/index.ts → dist/index.js");
await $`bun build src/index.ts --target node --outdir dist --external zod`.cwd(
	root,
);

console.log("[build] emitting dist/index.d.ts (tsc)");
await $`bunx tsc -p tsconfig.build.json`.cwd(root);

const outputs = [
	{
		file: "tree.schema.json",
		schema: (
			BehaviourNodeSchema as unknown as {
				toJSONSchema: (opts: { target: string }) => unknown;
			}
		).toJSONSchema({ target: "draft-2020-12" }),
	},
	{
		file: "workspace.schema.json",
		schema: (
			WorkspaceSchema as unknown as {
				toJSONSchema: (opts: { target: string }) => unknown;
			}
		).toJSONSchema({ target: "draft-2020-12" }),
	},
];

for (const { file, schema } of outputs) {
	const path = resolve(distDir, file);
	await writeFile(path, `${JSON.stringify(schema, null, 2)}\n`);
	console.log(`[build] wrote ${path}`);
}

console.log("[build] done");
